### ISSUE TITLE
How can I get proper baby name from age span?

### ISSUE THREAD

**Issue by GitOffice** [JasonKessler/agefromname#4]
AgeFromName is great work. I am twenty years old and am ready to study abroad. I want to own one foreign name. Dear JasonKessler , could you please tell me how to get a proper US name which fits the young aged twenty or so from AgeFromName's statistic?

**Comment by JasonKessler** [comment]
Just added the maximum_age constraint to the library, which should help you out.  I'll show you how to use AgeFromName to solve this problem.  Since I don't know your gender, I'll solve it for both. Note it involves using a protected function.

Below are the 20 most frequent female and male names of people born in 1998.  Note that you may want to look up common nicknames, since if you call yourself, for example, Christopher, people will probably end up calling your Chris.  

>>> age_from_name._get_estimated_counts_all_names('f', current_year=2018, minimum_age=20, maximum_age=20).sort_values(by='estimated_count', ascending=False).iloc[:20]
        first_name  year_of_birth  count  prob_alive  estimated_count
1274166      emily           1998  26179     0.98868     25882.642924
1274167     hannah           1998  21374     0.98868     21132.037505
1274168   samantha           1998  20192     0.98868     19963.418233
1274169      sarah           1998  19873     0.98868     19648.029444
1274170     ashley           1998  19871     0.98868     19646.052085
1274171     alexis           1998  19778     0.98868     19554.104884
1274172     taylor           1998  18572     0.98868     18361.757301
1274173    jessica           1998  18233     0.98868     18026.594921
1274174    madison           1998  17785     0.98868     17583.666466
1274175  elizabeth           1998  15179     0.98868     15007.167460
1274176     alyssa           1998  13710     0.98868     13554.797146
1274177      kayla           1998  13422     0.98868     13270.057425
1274178      megan           1998  13254     0.98868     13103.959254
1274179     lauren           1998  12907     0.98868     12760.887437
1274180     rachel           1998  12194     0.98868     12055.958891
1274181   victoria           1998  12144     0.98868     12006.524912
1274182    brianna           1998  12046     0.98868     11909.634312
1274183    abigail           1998  11099     0.98868     10973.354743
1274184     amanda           1998  10908     0.98868     10784.516942
1274185   jennifer           1998  10688     0.98868     10567.007432
>>> age_from_name._get_estimated_counts_all_names('m', current_year=2018, minimum_age=20, maximum_age=20).sort_values(by='estimated_count', ascending=False).iloc[:20]
          first_name  year_of_birth  count  prob_alive  estimated_count
1290762      michael           1998  36615    0.983588     36014.066230
1290763        jacob           1998  36007    0.983588     35416.044866
1290764      matthew           1998  31138    0.983588     30626.956009
1290765       joshua           1998  28086    0.983588     27625.046133
1290766  christopher           1998  26999    0.983588     26555.886226
1290767     nicholas           1998  26632    0.983588     26194.909514
1290768      brandon           1998  23828    0.983588     23436.929404
1290769        tyler           1998  23711    0.983588     23321.849635
1290770       andrew           1998  23648    0.983588     23259.883606
1290771       austin           1998  23477    0.983588     23091.690097
1290772       joseph           1998  23173    0.983588     22792.679414
1290773       daniel           1998  23143    0.983588     22763.171781
1290774        david           1998  20871    0.983588     20528.460366
1290775      william           1998  20827    0.983588     20485.182504
1290776         john           1998  20615    0.983588     20276.661897
1290777      zachary           1998  20579    0.983588     20241.252737
1290778         ryan           1998  20194    0.983588     19862.571445
1290779        james           1998  19683    0.983588     19359.958094
1290780      anthony           1998  19627    0.983588     19304.877179
1290781       justin           1998  17970    0.983588     17675.072243
```

**Comment by GitOffice** [comment]
@JasonKessler .  I appreciate all you have done for me and close this issue.
